baseURL = 'https://alertier.github.io/'
languageCode = 'zh-CN'
title = '电子科学学院请销假系统'

theme = "hyde"

[Menus]
  main = [
      {Name = "Github源码", URL = "https://github.com/Keyu30Zhang/information-system"},
  ]

[params]
  themeColor = "theme-base-0d"
  description = "信息系统分析与设计课程实验"